doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            activeUser:
                url: '%env(resolve:USER_DATABASE_URL)%'
        default_connection: default

    orm:
        default_entity_manager: default
        entity_managers:
            ActiveUser:
                connection: activeUser
                mappings:
                    ActiveUser:
                        is_bundle: false
                        dir: '%kernel.project_dir%/vendor/gryatka1/active-user/src/Entity'
                        prefix: 'ActiveUser\Entity'
                        alias: User
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Main
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
