version: '3.8'

services:
    family-task-php:
        container_name: family-task-php
        build:
            context: ./php
            args:
                - PUID=${PUID}
                - PGID=${PGID}
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        volumes:
            - ./../:/var/www/family-task
        networks:
            family:
                aliases:
                    - family-task-php
        restart: always
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    family-task-db:
        container_name: family-task-db
        image: postgres:15.4-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - db_data:/var/lib/postgresql/data:rw
        networks:
            family:
                aliases:
                    - family-task-db
        restart: always

networks:
    family:
        external: true

volumes:
    db_data: